truncate table specialty;

insert into specialty(name) values ('CONSULTAS');
insert into specialty(name) values ('MEDICINA INTERNA');
insert into specialty(name) values ('CARDIOLOGIA');
insert into specialty(name) values ('ENDOCRINOLOGIA');
insert into specialty(name) values ('GASTROENTEROLOGIA');
insert into specialty(name) values ('GERIATRIA E GERONTOLOGIA');
insert into specialty(name) values ('HEPATOLOGIA');
insert into specialty(name) values ('HEMATOLOGIA');
insert into specialty(name) values ('INFECTOLOGIA');
insert into specialty(name) values ('NEUROLOGIA');
insert into specialty(name) values ('PEDIATRIA');
insert into specialty(name) values ('PNEUMOLOGIA');
insert into specialty(name) values ('PSIQUIATRIA');
insert into specialty(name) values ('REUMATOLOGIA');
insert into specialty(name) values ('MEDICINA INTENSIVA');
insert into specialty(name) values ('NEFROLOGIA');
insert into specialty(name) values ('ANESTESIOLOGIA');
insert into specialty(name) values ('NUTRIÇÃO PARENTERAL E ENTERAL');
insert into specialty(name) values ('ALERGOLOGIA');
insert into specialty(name) values ('CARDIOLOGIA');
insert into specialty(name) values ('ANATOMIA PATOLÓGICA E CITOPATOLOGIA');
insert into specialty(name) values ('ELETROENCEFALOGRAFIA E NEUROFISIOLOGIA CLÍNICA');
insert into specialty(name) values ('ENDOSCOPIA DIGESTIVA');
insert into specialty(name) values ('ENDOSCOPIA PERORAL');
insert into specialty(name) values ('MEDICINA FÍSICA E REABILITAÇÃO');
insert into specialty(name) values ('GENÉTICA');
insert into specialty(name) values ('HEMOTERAPIA');
insert into specialty(name) values ('PATOLOGIA CLÍNICA');
insert into specialty(name) values ('TISIOPNEUMOLOGIA');
insert into specialty(name) values ('QUIMIOTERAPIA DO CÂNCER');
insert into specialty(name) values ('MEDICINA NUCLEAR');
insert into specialty(name) values ('RADIODIAGNÓSTICO');
insert into specialty(name) values ('ULTRA-SONOGRAFIA');
insert into specialty(name) values ('TOMOGRAFIA COMPUTADORIZADA');
insert into specialty(name) values ('RADIOTERAPIA');
insert into specialty(name) values ('RESSONÂNCIA MAGNÉTICA');
insert into specialty(name) values ('ANGIOLOGIA - CIRURGIA VASCULAR E LINFÁTICA');
insert into specialty(name) values ('CIRURGIA CARDÍACA - HEMODINÂMICA');
insert into specialty(name) values ('CIRURGIA DE CABEÇA E PESCOÇO');
insert into specialty(name) values ('DERMATOLOGIA CLÍNICO-CIRÚRGICA');
insert into specialty(name) values ('CIRURGIA DO APARELHO DIGESTIVO, ANEXOS E PAREDE ABDOMINAL');
insert into specialty(name) values ('CIRURGIA ENDOCRINOLÓGICA');
insert into specialty(name) values ('GINECOLOGIA E OBSTETRÍCIA');
insert into specialty(name) values ('MICROCIRURGIA RECONSTRUTIVA');
insert into specialty(name) values ('CIRURGIA DE MAMA');
insert into specialty(name) values ('CIRURGIA DA MÃO');
insert into specialty(name) values ('NEUROCIRURGIA');
insert into specialty(name) values ('OFTALMOLOGIA');
insert into specialty(name) values ('OTORRINOLARINGOLOGIA');
insert into specialty(name) values ('ORTOPEDIA E TRAUMATOLOGIA');
insert into specialty(name) values ('CIRURGIA PEDIÁTRICA');
insert into specialty(name) values ('CIRURGIA PLÁSTICA');
insert into specialty(name) values ('CIRURGIA TORÁCICA');
insert into specialty(name) values ('UROLOGIA');