truncate table material;

INSERT INTO material (`name`,`unit`) VALUES('Gaze','UN');
INSERT INTO material (`name`,`unit`) VALUES('Compressa cirurgica estéril','UN');
INSERT INTO material (`name`,`unit`) VALUES('Luvas de procedimentos','PAR');
INSERT INTO material (`name`,`unit`) VALUES('Lamina de bisturi descartável 15','UN');
INSERT INTO material (`name`,`unit`) VALUES('Micropore','METRO');
INSERT INTO material (`name`,`unit`) VALUES('Assepsia','UN');
INSERT INTO material (`name`,`unit`) VALUES('Luva estéril','PAR');
INSERT INTO material (`name`,`unit`) VALUES('Seringa descartável 10 cc','UN');
INSERT INTO material (`name`,`unit`) VALUES('Agulha 7 x 30','UN');
INSERT INTO material (`name`,`unit`) VALUES('Agulha 12 x 40','UN');
INSERT INTO material (`name`,`unit`) VALUES('Campo Estéril Fenestrado','UN');
INSERT INTO material (`name`,`unit`) VALUES('Agulha 5,5 x 30','UN');
INSERT INTO material (`name`,`unit`) VALUES('Agulhas 12 x 40','UN');
INSERT INTO material (`name`,`unit`) VALUES('Algodão 10 cm','UN');
INSERT INTO material (`name`,`unit`) VALUES('Stop blood','UN');
INSERT INTO material (`name`,`unit`) VALUES('Faixa de Crepe 10 cm','UN');
INSERT INTO material (`name`,`unit`) VALUES('Fita Crepe','METRO');
INSERT INTO material (`name`,`unit`) VALUES('ANESTESIA LOCAL','UN');
INSERT INTO material (`name`,`unit`) VALUES('Seringa 20 cc','UN');
INSERT INTO material (`name`,`unit`) VALUES('Faixa de Crepe 20 cm','UN');
INSERT INTO material (`name`,`unit`) VALUES('Seringa 10 cc','UN');
INSERT INTO material (`name`,`unit`) VALUES('Agulhas 7 x 30','UN');
INSERT INTO material (`name`,`unit`) VALUES('Luva de procedimentos','PAR');
INSERT INTO material (`name`,`unit`) VALUES('Seringa 5 cc','UN');
INSERT INTO material (`name`,`unit`) VALUES('Luva de procedimentos','UN');
INSERT INTO material (`name`,`unit`) VALUES('Lençol descartável','UN');
INSERT INTO material (`name`,`unit`) VALUES('Bisturi Descartável Estéril 15','UN');
INSERT INTO material (`name`,`unit`) VALUES('Dreno Penrose','UN');
INSERT INTO material (`name`,`unit`) VALUES('Mononylon 4,0','UN');
INSERT INTO material (`name`,`unit`) VALUES('Mononylon 3-0','UN');
INSERT INTO material (`name`,`unit`) VALUES('Faixa de Crepe 15 cm','UN');
INSERT INTO material (`name`,`unit`) VALUES('Algodão 15 cm','UN');
INSERT INTO material (`name`,`unit`) VALUES('Luva para procedimento','PAR');
INSERT INTO material (`name`,`unit`) VALUES('Luva para procedimento','UN');
INSERT INTO material (`name`,`unit`) VALUES('Mononylon 4-0','UN');
INSERT INTO material (`name`,`unit`) VALUES('Bisturi Elétrico','UN');
INSERT INTO material (`name`,`unit`) VALUES('Algodão 20 cm','UN');
INSERT INTO material (`name`,`unit`) VALUES('Luvas de procedimento','PAR');
INSERT INTO material (`name`,`unit`) VALUES('Faixa crepe 15 cm','UN');
INSERT INTO material (`name`,`unit`) VALUES('Fita Crepe','UN');
INSERT INTO material (`name`,`unit`) VALUES('Lenol Descartável','UN');
INSERT INTO material (`name`,`unit`) VALUES('Bisturi Descartável Estéril 20','UN');
INSERT INTO material (`name`,`unit`) VALUES('Faixa de crepe de 20 cm','UN');
INSERT INTO material (`name`,`unit`) VALUES('Luvas de procedimento','UN');
INSERT INTO material (`name`,`unit`) VALUES('Faixa crepe 10 cm','UN');
INSERT INTO material (`name`,`unit`) VALUES('Malha Tubular 08 cm','METRO');
INSERT INTO material (`name`,`unit`) VALUES('Malha Tubular 15 cm','METRO');
INSERT INTO material (`name`,`unit`) VALUES('Malha Tubular 30 cm','METRO');
INSERT INTO material (`name`,`unit`) VALUES('Luva Descartável','PAR');
INSERT INTO material (`name`,`unit`) VALUES('Malha Tubular 10 cm','METRO');
INSERT INTO material (`name`,`unit`) VALUES('Esparadrapo','METRO');
INSERT INTO material (`name`,`unit`) VALUES('Gesso 15 cm','UN');
INSERT INTO material (`name`,`unit`) VALUES('Gesso 10 cm','UN');
INSERT INTO material (`name`,`unit`) VALUES('Malha Tubular 20 cm','METRO');
INSERT INTO material (`name`,`unit`) VALUES('Gesso 20 cm','UN');
INSERT INTO material (`name`,`unit`) VALUES('Avental Descartável','UN');
INSERT INTO material (`name`,`unit`) VALUES('Salto','UN');
INSERT INTO material (`name`,`unit`) VALUES('Tala Metálica','UN');
INSERT INTO material (`name`,`unit`) VALUES('Seringa de 10 ml','UN');
INSERT INTO material (`name`,`unit`) VALUES('Agulhas 30 x 7','UN');
INSERT INTO material (`name`,`unit`) VALUES('Bisturi descarável 15','UN');
INSERT INTO material (`name`,`unit`) VALUES('Campo fenestrado descartável','UN');
INSERT INTO material (`name`,`unit`) VALUES('Mononylon 5-0','UN');
INSERT INTO material (`name`,`unit`) VALUES('Luvas','UN');
INSERT INTO material (`name`,`unit`) VALUES('Seringa 10cc','UN');
INSERT INTO material (`name`,`unit`) VALUES('Agulha 13x3','UN');
INSERT INTO material (`name`,`unit`) VALUES('Gazes esteril','PACOTE');
INSERT INTO material (`name`,`unit`) VALUES('Micropore','CENTIMETRO');
INSERT INTO material (`name`,`unit`) VALUES('Mascara cirúrgica descartável','UN');
INSERT INTO material (`name`,`unit`) VALUES('Gorro cirúrgico','UN');
INSERT INTO material (`name`,`unit`) VALUES('Fio mononylon 4-0','UN');
INSERT INTO material (`name`,`unit`) VALUES ('Filme 0,1296', UPPER('Un'));
INSERT INTO material (`name`,`unit`) VALUES ('Filme 0,3120', UPPER('Un'));
INSERT INTO material (`name`,`unit`) VALUES ('Filme 0,1728', UPPER('Un'));
INSERT INTO material (`name`,`unit`) VALUES ('Filme 0,0864', UPPER('Un'));
INSERT INTO material (`name`,`unit`) VALUES ('Filme 0,1920', UPPER('Un'));
INSERT INTO material (`name`,`unit`) VALUES ('Filme 0,1872', UPPER('Un'));
INSERT INTO material (`name`,`unit`) VALUES ('Filme 0,2400', UPPER('Un'));
INSERT INTO material (`name`,`unit`) VALUES ('Filme 0,1440', UPPER('Un'));
INSERT INTO material (`name`,`unit`) VALUES ('Filme 0,1540', UPPER('Un'));
INSERT INTO material (`name`,`unit`) VALUES ('Filme 0,3080', UPPER('Un'));
INSERT INTO material (`name`,`unit`) VALUES ('Filme 0,2160', UPPER('Un'));