var i18n = $.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "ddMMyyyy",
            "fulldayshow": "L d yyyy",
            "fulldayvalue": "d/M/yyyy",
            "Md": "W d/M",
            "Md3": "L d",
            "separator": "/",
            "year_index": 2,
            "month_index": 1,
            "day_index": 0,
            "day": "d",
            "sun": "Dom",
            "mon": "Seg",
            "tue": "Ter",
            "wed": "Qua",
            "thu": "Qui",
            "fri": "Sex",
            "sat": "Sab",
            "jan": "Jan",
            "feb": "Fev",
            "mar": "Mar",
            "apr": "Abr",
            "may": "Mai",
            "jun": "Jun",
            "jul": "Jul",
            "aug": "Ago",
            "sep": "Set",
            "oct": "Out",
            "nov": "Nov",
            "dec": "Dez"
        },
        "no_implemented": "Em implementação",
        "to_date_view": "CLique para ver o dia atual",
        "i_undefined": "Não definido",
        "allday_event": "Compromissos diários",
        "repeat_event": "Compromissos repetitivos",
        "time": "Horário",
        "event": "Compromisso",
        "location": "Local",
        "participant": "Participante",
        "get_data_exception": "Falha ao definir data",
        "new_event": "Novo Compromisso",
        "confirm_delete_event": "Deseja realmente deletar esse compromisso? ",
        "confrim_delete_event_or_all": "Do you want to all repeat events or only this event? \r\nClick [OK] to delete only this event, click [Cancel] delete all events",
        "data_format_error": "Formato de data inválido! ",
        "invalid_title": "O título do compromisso é obrigatório.",
        "view_no_ready": "Agenda não pode ser lida",
        "example": "consulta com o paciente Fulano na sala 43.",
        "content": "O que",
        "create_event": "Criar Compromisso",
        "update_detail": "Editar Compromisso",
        "click_to_detail": "Visualizar Compromisso",
        "i_delete": "Deletar",
        "day_plural": "dias",
        "others": "Outros",
        "item": ""
    }
});
